import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id);

export const products: Product[] = [
  {
    id: '1',
    name: 'Elegant Maroon Silk Saree',
    description: 'A stunning maroon silk saree with intricate zari work, perfect for weddings and festive occasions.',
    price: 4999,
    image: getImage('saree-1')?.imageUrl || '',
    imageHint: getImage('saree-1')?.imageHint || '',
    category: 'Silk',
    color: 'Maroon',
    fabric: 'Silk',
    rating: 4.8,
    reviewCount: 120,
    occasion: 'Wedding, Festive',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '2',
    name: 'Royal Blue Banarasi Saree',
    description: 'Feel like royalty in this exquisite Banarasi saree. Features a rich blue color and traditional motifs.',
    price: 7500,
    image: getImage('saree-2')?.imageUrl || '',
    imageHint: getImage('saree-2')?.imageHint || '',
    category: 'Banarasi',
    color: 'Blue',
    fabric: 'Banarasi Silk',
    rating: 4.9,
    reviewCount: 95,
    occasion: 'Wedding, Grand Events',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '3',
    name: 'Pastel Green Chiffon Saree',
    description: 'A light and airy chiffon saree in a soothing pastel green. Ideal for daytime events and summer parties.',
    price: 2800,
    image: getImage('saree-3')?.imageUrl || '',
    imageHint: getImage('saree-3')?.imageHint || '',
    category: 'Chiffon',
    color: 'Green',
    fabric: 'Chiffon',
    rating: 4.5,
    reviewCount: 78,
    occasion: 'Daytime Event, Casual',
    careInstructions: 'Gentle hand wash.',
  },
  {
    id: '4',
    name: 'Classic Kanjivaram Saree',
    description: 'A timeless Kanjivaram silk saree with a contrasting border. A must-have for every saree connoisseur.',
    price: 12500,
    image: getImage('saree-4')?.imageUrl || '',
    imageHint: getImage('saree-4')?.imageHint || '',
    category: 'Kanjivaram',
    color: 'Red',
    fabric: 'Kanjivaram Silk',
    rating: 5.0,
    reviewCount: 210,
    occasion: 'Bridal, Temple Wear',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '5',
    name: 'Simple Off-white Cotton Saree',
    description: 'Elegant and comfortable, this off-white cotton saree is perfect for office or casual wear.',
    price: 1500,
    image: getImage('saree-5')?.imageUrl || '',
    imageHint: getImage('saree-5')?.imageHint || '',
    category: 'Cotton',
    color: 'White',
    fabric: 'Cotton',
    rating: 4.6,
    reviewCount: 150,
    occasion: 'Office, Casual Wear',
    careInstructions: 'Hand wash separately in cold water.',
  },
  {
    id: '6',
    name: 'Modern Georgette Saree',
    description: 'A chic and modern georgette saree with a minimalist design. Easy to drape and carry.',
    price: 3200,
    image: getImage('saree-6')?.imageUrl || '',
    imageHint: getImage('saree-6')?.imageHint || '',
    category: 'Georgette',
    color: 'Black',
    fabric: 'Georgette',
    rating: 4.7,
    reviewCount: 88,
    occasion: 'Party, Evening Wear',
    careInstructions: 'Gentle hand wash.',
  },
  {
    id: '7',
    name: 'Golden Yellow Silk Saree',
    description: 'Bright and beautiful, this yellow silk saree exudes radiance. Perfect for daytime celebrations.',
    price: 5200,
    image: getImage('saree-7')?.imageUrl || '',
    imageHint: getImage('saree-7')?.imageHint || '',
    category: 'Silk',
    color: 'Yellow',
    fabric: 'Art Silk',
    rating: 4.7,
    reviewCount: 110,
    occasion: 'Festive, Haldi Ceremony',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '8',
    name: 'Ivory White Organza Saree',
    description: 'An ethereal organza saree in ivory white, featuring delicate embroidery. For the modern woman.',
    price: 4500,
    image: getImage('saree-8')?.imageUrl || '',
    imageHint: getImage('saree-8')?.imageHint || '',
    category: 'Organza',
    color: 'White',
    fabric: 'Organza',
    rating: 4.8,
    reviewCount: 90,
    occasion: 'Party, Cocktail',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '9',
    name: 'Emerald Green Banarasi Saree',
    description: 'A luxurious Banarasi saree in a rich emerald green, woven with golden threads.',
    price: 8200,
    image: getImage('saree-9')?.imageUrl || '',
    imageHint: getImage('saree-9')?.imageHint || '',
    category: 'Banarasi',
    color: 'Green',
    fabric: 'Banarasi Silk',
    rating: 4.9,
    reviewCount: 130,
    occasion: 'Wedding, Reception',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '10',
    name: 'Deep Blue Georgette Saree',
    description: 'A flowing georgette saree in a captivating deep blue, adorned with subtle sequins.',
    price: 3800,
    image: getImage('saree-10')?.imageUrl || '',
    imageHint: getImage('saree-10')?.imageHint || '',
    category: 'Georgette',
    color: 'Blue',
    fabric: 'Georgette',
    rating: 4.6,
    reviewCount: 85,
    occasion: 'Evening Party, Farewell',
    careInstructions: 'Gentle hand wash.',
  },
  {
    id: '11',
    name: 'Soft Pink Cotton Saree',
    description: 'A breathable cotton saree in a lovely soft pink. Perfect for summer days and casual outings.',
    price: 1800,
    image: getImage('saree-11')?.imageUrl || '',
    imageHint: getImage('saree-11')?.imageHint || '',
    category: 'Cotton',
    color: 'Pink',
    fabric: 'Cotton',
    rating: 4.7,
    reviewCount: 180,
    occasion: 'Casual, Daily Wear',
    careInstructions: 'Hand wash separately.',
  },
  {
    id: '12',
    name: 'Majestic Purple Kanjivaram Saree',
    description: 'Drape yourself in splendor with this purple Kanjivaram, featuring traditional temple borders.',
    price: 14000,
    image: getImage('saree-12')?.imageUrl || '',
    imageHint: getImage('saree-12')?.imageHint || '',
    category: 'Kanjivaram',
    color: 'Purple',
    fabric: 'Kanjivaram Silk',
    rating: 4.9,
    reviewCount: 150,
    occasion: 'Bridal, Grand Occasions',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '13',
    name: 'Floral Printed Chiffon Saree',
    description: 'A vibrant chiffon saree with a beautiful floral print. Lightweight and perfect for a breezy day.',
    price: 2600,
    image: getImage('saree-13')?.imageUrl || '',
    imageHint: getImage('saree-13')?.imageHint || '',
    category: 'Chiffon',
    color: 'Multicolor',
    fabric: 'Chiffon',
    rating: 4.4,
    reviewCount: 65,
    occasion: 'Casual, Brunch',
    careInstructions: 'Gentle hand wash.',
  },
  {
    id: '14',
    name: 'Black and Gold Silk Saree',
    description: 'A classic combination of black and gold in a lustrous silk fabric. The epitome of elegance.',
    price: 6500,
    image: getImage('saree-14')?.imageUrl || '',
    imageHint: getImage('saree-14')?.imageHint || '',
    category: 'Silk',
    color: 'Black',
    fabric: 'Silk',
    rating: 4.8,
    reviewCount: 140,
    occasion: 'Party, Formal Event',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '15',
    name: 'Handwoven Linen Saree',
    description: 'An earthy and elegant handwoven linen saree, known for its comfort and sophisticated look.',
    price: 3500,
    image: getImage('saree-15')?.imageUrl || '',
    imageHint: getImage('saree-15')?.imageHint || '',
    category: 'Linen',
    color: 'Beige',
    fabric: 'Linen',
    rating: 4.7,
    reviewCount: 95,
    occasion: 'Office, Formal',
    careInstructions: 'Gentle hand wash or dry clean.',
  },
  {
    id: '16',
    name: 'Peach Tussar Silk Saree',
    description: 'A graceful Tussar silk saree in a warm peach shade, with a unique texture and natural sheen.',
    price: 5800,
    image: getImage('saree-16')?.imageUrl || '',
    imageHint: getImage('saree-16')?.imageHint || '',
    category: 'Silk',
    color: 'Peach',
    fabric: 'Tussar Silk',
    rating: 4.8,
    reviewCount: 80,
    occasion: 'Festive, Daytime Event',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '17',
    name: 'Grey Art Silk Saree',
    description: 'A contemporary art silk saree in a sophisticated grey, perfect for a modern and chic look.',
    price: 2900,
    image: getImage('saree-17')?.imageUrl || '',
    imageHint: getImage('saree-17')?.imageHint || '',
    category: 'Silk',
    color: 'Grey',
    fabric: 'Art Silk',
    rating: 4.5,
    reviewCount: 70,
    occasion: 'Office, Casual Party',
    careInstructions: 'Gentle machine wash.',
  },
  {
    id: '18',
    name: 'Traditional Patola Saree',
    description: 'A vibrant and intricate Patola saree, showcasing the rich heritage of Gujarati weaving.',
    price: 18000,
    image: getImage('saree-18')?.imageUrl || '',
    imageHint: getImage('saree-18')?.imageHint || '',
    category: 'Patola',
    color: 'Multicolor',
    fabric: 'Silk',
    rating: 5.0,
    reviewCount: 110,
    occasion: 'Wedding, Cultural Event',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '19',
    name: 'Contemporary Bandhani Saree',
    description: 'A modern take on the traditional Bandhani tie-dye technique, in a soft georgette fabric.',
    price: 4200,
    image: getImage('saree-19')?.imageUrl || '',
    imageHint: getImage('saree-19')?.imageHint || '',
    category: 'Bandhani',
    color: 'Red',
    fabric: 'Georgette',
    rating: 4.7,
    reviewCount: 90,
    occasion: 'Festive, Navratri',
    careInstructions: 'Dry clean recommended.',
  },
  {
    id: '20',
    name: 'Elegant Cream Chanderi Saree',
    description: 'Lightweight and sheer, this Chanderi saree in cream is a picture of grace and subtlety.',
    price: 3900,
    image: getImage('saree-20')?.imageUrl || '',
    imageHint: getImage('saree-20')?.imageHint || '',
    category: 'Chanderi',
    color: 'Cream',
    fabric: 'Chanderi Silk',
    rating: 4.8,
    reviewCount: 85,
    occasion: 'Formal, Daytime Event',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '21',
    name: 'Authentic Pochampally Ikat Saree',
    description: 'A stunning Pochampally Ikat saree featuring bold geometric patterns, a masterpiece from Telangana.',
    price: 9500,
    image: getImage('saree-21')?.imageUrl || '',
    imageHint: getImage('saree-21')?.imageHint || '',
    category: 'Pochampally',
    color: 'Maroon',
    fabric: 'Silk',
    rating: 4.9,
    reviewCount: 75,
    occasion: 'Cultural Event, Formal',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '22',
    name: 'Light Blue Kota Doria Saree',
    description: 'Feather-light Kota Doria saree from Rajasthan with a classic check pattern. Perfect for hot weather.',
    price: 2200,
    image: getImage('saree-22')?.imageUrl || '',
    imageHint: getImage('saree-22')?.imageHint || '',
    category: 'Kota Doria',
    color: 'Blue',
    fabric: 'Cotton-Silk Blend',
    rating: 4.6,
    reviewCount: 115,
    occasion: 'Casual, Office Wear',
    careInstructions: 'Gentle hand wash.',
  },
  {
    id: '23',
    name: 'Vibrant Orange Bandhani Saree',
    description: 'A lively orange Bandhani saree from Gujarat, perfect for festive celebrations and Navratri.',
    price: 4800,
    image: getImage('saree-23')?.imageUrl || '',
    imageHint: getImage('saree-23')?.imageHint || '',
    category: 'Bandhani',
    color: 'Orange',
    fabric: 'Georgette',
    rating: 4.7,
    reviewCount: 98,
    occasion: 'Festive, Garba Night',
    careInstructions: 'Dry clean recommended.',
  },
  {
    id: '24',
    name: 'Classic White and Red Tant Saree',
    description: 'A traditional Bengali Tant saree, crisp and elegant, with a classic red border on a white body.',
    price: 1900,
    image: getImage('saree-24')?.imageUrl || '',
    imageHint: getImage('saree-24')?.imageHint || '',
    category: 'Tant',
    color: 'White',
    fabric: 'Cotton',
    rating: 4.8,
    reviewCount: 250,
    occasion: 'Pooja, Daily Wear',
    careInstructions: 'Hand wash with starch.',
  },
  {
    id: '25',
    name: 'Royal Mysore Silk Saree',
    description: 'A minimalist yet luxurious Mysore Silk saree, known for its purity and subtle sheen.',
    price: 11000,
    image: getImage('saree-25')?.imageUrl || '',
    imageHint: getImage('saree-25')?.imageHint || '',
    category: 'Silk',
    color: 'Gold',
    fabric: 'Mysore Silk',
    rating: 4.9,
    reviewCount: 140,
    occasion: 'Formal, Wedding',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '26',
    name: 'Teal Blue Chanderi Saree',
    description: 'An elegant Chanderi saree in a unique teal blue, with delicate buttis and a sheer texture.',
    price: 4100,
    image: getImage('saree-26')?.imageUrl || '',
    imageHint: getImage('saree-26')?.imageHint || '',
    category: 'Chanderi',
    color: 'Blue',
    fabric: 'Chanderi Silk',
    rating: 4.7,
    reviewCount: 77,
    occasion: 'Daytime Event, Party',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '27',
    name: 'Crimson Red Georgette Saree',
    description: 'A bold and beautiful crimson red georgette saree, perfect for making a statement.',
    price: 3400,
    image: getImage('saree-27')?.imageUrl || '',
    imageHint: getImage('saree-27')?.imageHint || '',
    category: 'Georgette',
    color: 'Red',
    fabric: 'Georgette',
    rating: 4.6,
    reviewCount: 102,
    occasion: 'Party, Farewell',
    careInstructions: 'Gentle hand wash.',
  },
  {
    id: '28',
    name: 'Sunshine Yellow Cotton Saree',
    description: 'A cheerful yellow cotton saree, ideal for summer days and casual wear, keeping you cool and stylish.',
    price: 1650,
    image: getImage('saree-28')?.imageUrl || '',
    imageHint: getImage('saree-28')?.imageHint || '',
    category: 'Cotton',
    color: 'Yellow',
    fabric: 'Cotton',
    rating: 4.5,
    reviewCount: 160,
    occasion: 'Casual, Daily Wear',
    careInstructions: 'Hand wash separately.',
  },
  {
    id: '29',
    name: 'Midnight Blue Kanjivaram',
    description: 'A stunning Kanjivaram in midnight blue with silver zari work, offering a contemporary twist to tradition.',
    price: 13500,
    image: getImage('saree-29')?.imageUrl || '',
    imageHint: getImage('saree-29')?.imageHint || '',
    category: 'Kanjivaram',
    color: 'Blue',
    fabric: 'Kanjivaram Silk',
    rating: 4.9,
    reviewCount: 180,
    occasion: 'Reception, Grand Events',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '30',
    name: 'Lavender Organza Saree',
    description: 'A dreamy lavender organza saree with light sequin work, perfect for evening parties.',
    price: 4800,
    image: getImage('saree-30')?.imageUrl || '',
    imageHint: getImage('saree-30')?.imageHint || '',
    category: 'Organza',
    color: 'Purple',
    fabric: 'Organza',
    rating: 4.8,
    reviewCount: 95,
    occasion: 'Cocktail, Party',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '31',
    name: 'Wine Red Velvet Saree',
    description: 'A luxurious velvet saree in a rich wine red, perfect for winter weddings and formal events.',
    price: 8900,
    image: getImage('saree-31')?.imageUrl || '',
    imageHint: getImage('saree-31')?.imageHint || '',
    category: 'Velvet',
    color: 'Red',
    fabric: 'Velvet',
    rating: 4.9,
    reviewCount: 60,
    occasion: 'Winter Wedding, Reception',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '32',
    name: 'Black Shimmer Chiffon Saree',
    description: 'A glamorous black chiffon saree with all-over shimmer, designed for the party-goer.',
    price: 3100,
    image: getImage('saree-32')?.imageUrl || '',
    imageHint: getImage('saree-32')?.imageHint || '',
    category: 'Chiffon',
    color: 'Black',
    fabric: 'Chiffon',
    rating: 4.6,
    reviewCount: 110,
    occasion: 'Party, Evening Wear',
    careInstructions: 'Gentle hand wash.',
  },
  {
    id: '33',
    name: 'Forest Green Linen Saree',
    description: 'A sophisticated linen saree in a deep forest green, perfect for a classy and understated look.',
    price: 3700,
    image: getImage('saree-33')?.imageUrl || '',
    imageHint: getImage('saree-33')?.imageHint || '',
    category: 'Linen',
    color: 'Green',
    fabric: 'Linen',
    rating: 4.7,
    reviewCount: 88,
    occasion: 'Office, Formal',
    careInstructions: 'Gentle hand wash or dry clean.',
  },
  {
    id: '34',
    name: 'Royal Green Paithani Saree',
    description: 'A traditional Paithani saree from Maharashtra with a signature peacock pallu in royal green.',
    price: 16000,
    image: getImage('saree-34')?.imageUrl || '',
    imageHint: getImage('saree-34')?.imageHint || '',
    category: 'Paithani',
    color: 'Green',
    fabric: 'Silk',
    rating: 5.0,
    reviewCount: 95,
    occasion: 'Bridal, Wedding',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '35',
    name: 'Beige and Gold Kerala Kasavu Saree',
    description: 'The iconic Kasavu saree from Kerala, known for its elegant simplicity and golden border.',
    price: 4500,
    image: getImage('saree-35')?.imageUrl || '',
    imageHint: getImage('saree-35')?.imageHint || '',
    category: 'Kasavu',
    color: 'Beige',
    fabric: 'Cotton',
    rating: 4.9,
    reviewCount: 300,
    occasion: 'Onam, Temple Wear, Festive',
    careInstructions: 'Gentle hand wash or dry clean.',
  },
  {
    id: '36',
    name: 'Fuchsia Pink Banarasi Silk Saree',
    description: 'A vibrant fuchsia pink Banarasi silk saree, woven with intricate floral jaal work.',
    price: 8500,
    image: getImage('saree-36')?.imageUrl || '',
    imageHint: getImage('saree-36')?.imageHint || '',
    category: 'Banarasi',
    color: 'Pink',
    fabric: 'Banarasi Silk',
    rating: 4.8,
    reviewCount: 125,
    occasion: 'Wedding, Festive',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '37',
    name: 'Indigo Blue Ajrakh Print Saree',
    description: 'A beautiful cotton saree featuring the traditional Ajrakh block printing from Gujarat in indigo blue.',
    price: 2800,
    image: getImage('saree-37')?.imageUrl || '',
    imageHint: getImage('saree-37')?.imageHint || '',
    category: 'Cotton',
    color: 'Blue',
    fabric: 'Cotton',
    rating: 4.7,
    reviewCount: 140,
    occasion: 'Casual, Ethnic Day',
    careInstructions: 'Hand wash separately in cold water.',
  },
  {
    id: '38',
    name: 'Turquoise Blue Silk Saree',
    description: 'A lustrous silk saree in a striking turquoise blue, simple yet elegant for any special occasion.',
    price: 6200,
    image: getImage('saree-38')?.imageUrl || '',
    imageHint: getImage('saree-38')?.imageHint || '',
    category: 'Silk',
    color: 'Blue',
    fabric: 'Art Silk',
    rating: 4.6,
    reviewCount: 92,
    occasion: 'Festive, Party',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '39',
    name: 'Charcoal Grey Tussar Silk Saree',
    description: 'A sophisticated Tussar silk saree in charcoal grey, with a unique texture and subtle elegance.',
    price: 5900,
    image: getImage('saree-39')?.imageUrl || '',
    imageHint: getImage('saree-39')?.imageHint || '',
    category: 'Silk',
    color: 'Grey',
    fabric: 'Tussar Silk',
    rating: 4.8,
    reviewCount: 78,
    occasion: 'Formal, Official Party',
    careInstructions: 'Dry clean only.',
  },
  {
    id: '40',
    name: 'Multicolor Digital Print Organza Saree',
    description: 'A contemporary organza saree with an abstract multicolor digital print, perfect for a fashion-forward look.',
    price: 4950,
    image: getImage('saree-40')?.imageUrl || '',
    imageHint: getImage('saree-40')?.imageHint || '',
    category: 'Organza',
    color: 'Multicolor',
    fabric: 'Organza',
    rating: 4.7,
    reviewCount: 85,
    occasion: 'Party, Cocktail',
    careInstructions: 'Dry clean only.',
  }
];

export const categories = [
  { name: 'All', href: '/products' },
  { name: 'Silk', href: '/products?category=Silk' },
  { name: 'Banarasi', href: '/products?category=Banarasi' },
  { name: 'Chiffon', href: '/products?category=Chiffon' },
  { name: 'Kanjivaram', href: '/products?category=Kanjivaram' },
  { name: 'Cotton', href: '/products?category=Cotton' },
  { name: 'Georgette', href: '/products?category=Georgette' },
  { name: 'Organza', href: '/products?category=Organza'},
  { name: 'Linen', href: '/products?category=Linen'},
  { name: 'Patola', href: '/products?category=Patola'},
  { name: 'Bandhani', href: '/products?category=Bandhani'},
  { name: 'Chanderi', href: '/products?category=Chanderi'},
  { name: 'Pochampally', href: '/products?category=Pochampally' },
  { name: 'Kota Doria', href: '/products?category=Kota Doria' },
  { name: 'Tant', href: '/products?category=Tant' },
  { name: 'Velvet', href: '/products?category=Velvet' },
  { name: 'Paithani', href: '/products?category=Paithani' },
  { name: 'Kasavu', href: '/products?category=Kasavu' },
];
