import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id);

export const products: Product[] = [
  {
    id: '1',
    name: 'Elegant Maroon Silk Saree',
    description: 'A stunning maroon silk saree with intricate zari work, perfect for weddings and festive occasions.',
    price: 4999,
    image: getImage('saree-1')?.imageUrl || '',
    imageHint: getImage('saree-1')?.imageHint || '',
    category: 'Silk',
    color: 'Maroon',
    fabric: 'Silk',
    rating: 4.8,
    reviewCount: 120,
  },
  {
    id: '2',
    name: 'Royal Blue Banarasi Saree',
    description: 'Feel like royalty in this exquisite Banarasi saree. Features a rich blue color and traditional motifs.',
    price: 7500,
    image: getImage('saree-2')?.imageUrl || '',
    imageHint: getImage('saree-2')?.imageHint || '',
    category: 'Banarasi',
    color: 'Blue',
    fabric: 'Banarasi Silk',
    rating: 4.9,
    reviewCount: 95,
  },
  {
    id: '3',
    name: 'Pastel Green Chiffon Saree',
    description: 'A light and airy chiffon saree in a soothing pastel green. Ideal for daytime events and summer parties.',
    price: 2800,
    image: getImage('saree-3')?.imageUrl || '',
    imageHint: getImage('saree-3')?.imageHint || '',
    category: 'Chiffon',
    color: 'Green',
    fabric: 'Chiffon',
    rating: 4.5,
    reviewCount: 78,
  },
  {
    id: '4',
    name: 'Classic Kanjivaram Saree',
    description: 'A timeless Kanjivaram silk saree with a contrasting border. A must-have for every saree connoisseur.',
    price: 12500,
    image: getImage('saree-4')?.imageUrl || '',
    imageHint: getImage('saree-4')?.imageHint || '',
    category: 'Kanjivaram',
    color: 'Red',
    fabric: 'Kanjivaram Silk',
    rating: 5.0,
    reviewCount: 210,
  },
  {
    id: '5',
    name: 'Simple Off-white Cotton Saree',
    description: 'Elegant and comfortable, this off-white cotton saree is perfect for office or casual wear.',
    price: 1500,
    image: getImage('saree-5')?.imageUrl || '',
    imageHint: getImage('saree-5')?.imageHint || '',
    category: 'Cotton',
    color: 'White',
    fabric: 'Cotton',
    rating: 4.6,
    reviewCount: 150,
  },
  {
    id: '6',
    name: 'Modern Georgette Saree',
    description: 'A chic and modern georgette saree with a minimalist design. Easy to drape and carry.',
    price: 3200,
    image: getImage('saree-6')?.imageUrl || '',
    imageHint: getImage('saree-6')?.imageHint || '',
    category: 'Georgette',
    color: 'Black',
    fabric: 'Georgette',
    rating: 4.7,
    reviewCount: 88,
  },
];

export const categories = [
  { name: 'All', href: '/products' },
  { name: 'Silk', href: '/products?category=Silk' },
  { name: 'Banarasi', href: '/products?category=Banarasi' },
  { name: 'Chiffon', href: '/products?category=Chiffon' },
  { name: 'Kanjivaram', href: '/products?category=Kanjivaram' },
  { name: 'Cotton', href: '/products?category=Cotton' },
  { name: 'Georgette', href: '/products?category=Georgette' },
];
